### ISSUE TITLE
blue screen system(

### ISSUE THREAD

**Issue by xSanx** [fdiskyou/windows-ps-callbacks-experiments#1]
hi, i read your blog, and I am impressed with the work done. But i run evilcli i get blue screen system. i work in windows 10 x64 17763, 18363 and 19041...

**Comment by fdiskyou** [comment]
That's intentional. As the main `README.md` file says, **only** Windows 10 19H1 x64 is "supported". It's easy to make it work with any other Windows 10 version, but you'll have to hack the code.
